### ISSUE TITLE
浏览器兼容问题

### ISSUE THREAD

**Issue by testwen00** [MarkRepo/wfs.js#2]
你好，有2个问题，咨询下
1、firefox下播放不太正常，画面错乱了，延时严重，ie下播放不了。
2、chrome下播放可以，但是一切换到其他页面，隔段时间切换回来看，画面就停止了。像是停止渲染，连接并没有断开。

thanks

**Comment by MarkRepo** [comment]
1. 暂时只支持chrome, 没有考虑移植性
2. 标签页切换后，原来的标签是会暂停解码播放的，但是数据还在接收，有可能隔的时间过长导致浏览器缓冲区溢出，丢失一些数据，h264 是会解码不了的. 所以这里需要自己处理，要么切回来时刷新一下，要么切换标签页时丢弃收到的数据，切回时获取关键帧开始一个新的解码序列。
