### ISSUE TITLE
There is a error

### ISSUE THREAD

**Issue by huge818** [MarkRepo/wfs.js#4]
./wfs_websockets_hub.go:27: multiple-value uuid.NewV4() in single-value context

**Comment by huge818** [comment]
Ubuntu16.04   x64

**Comment by kinpol** [comment]
get the previous verion of golang,(not go 1.10). 
$  go version
go version go1.9.2 linux/amd64

**Comment by chenchenwuai** [comment]
> ./wfs_websockets_hub.go:27：单值上下文中的多值uuid.NewV4（）
`u1,_ := uuid.NewV4() `
试试这个

**Comment by MarkRepo** [comment]
不记得了，环境问题不负责解答
