### ISSUE TITLE
单页面多个websocket？

### ISSUE THREAD

**Issue by chenchenwuai** [MarkRepo/wfs.js#5]
请问支持单页面多个websocket吗？还有我的每个websocket接收到数据后都要在解析一下帧头，请问支持吗？在线等

**Comment by kinpol** [comment]
支持,我们测试到8路1080p

**Comment by chenchenwuai** [comment]
你好，目前我测试的8路1080,内存增加的很快（10分钟内存增加2G），你们会出现这种情况吗

**Comment by kinpol** [comment]
不管开几个video，浏览器都只buffer到1GB多点儿稳定了.

**Comment by MarkRepo** [comment]
单页面多个websocket, 是指连多个虚拟机吗？

**Comment by chenchenwuai** [comment]
> 不管开几个视频，浏览器都只缓冲到1GB多点儿稳定了。

可以交流一下吗？我的在chrome上播放8路1080p视频（内网千兆交换机），内存一直增长，测试过谷歌会在5G左右,火狐无限增长。

**Comment by MarkRepo** [comment]
chrome 会缓存视频的，需要自己定期清空缓存

**Comment by MarkRepo** [comment]
如果你不嫌麻烦的话，可以参考我的spice web client里面的做法

**Comment by chenchenwuai** [comment]
![image](https://user-images.githubusercontent.com/32892396/50682873-376d1c80-104b-11e9-9efe-39b91813e808.png)

对于这一段我有点模糊，能给一个实际的例子吗？我主要是不知道从哪获取 played.end()和buffer.start()。

**Comment by MarkRepo** [comment]
https://github.com/MarkRepo/spice_web_client/blob/master/wfs.js/src/controller/buffer-controller.js 这个文件的onSBUpdateEnd函数

**Comment by chenchenwuai** [comment]
太感谢了，完美解决了我的问题。thank u.
