### ISSUE TITLE
(1)長時間影像delay & (2)約10 hrs 後影像斷了 

### ISSUE THREAD

**Issue by DavidDong33** [MarkRepo/wfs.js#6]
(1)播放一段時間後影像delay數秒
(2)長時間播放, 偵測到 error message: 
	wfs.js:1711 internal error happened while processing wfsBufferAppending:ErrorTypes is not defined 

Thanks.

**Comment by kinpol** [comment]
（1）检查帧率的设置。我们自己测试，实时性在1秒之内。https://github.com/ChihChengYang/wfs.js/issues/1
（2）测试一下视频帧。在浏览器端保存文件，再对比源文件，逐帧查看问题。

**Comment by MarkRepo** [comment]
可以参考我的spice_web_client项目。

**Comment by zhang22113** [comment]
> 可以参考我的spice_web_client项目。

我也遇到了这个问题，每次播放到13个小时15分钟21秒时，就卡住了
