### ISSUE TITLE
能不能出一个把websocket分离出来的版本？

### ISSUE THREAD

**Issue by chenchenwuai** [MarkRepo/wfs.js#8]
能不能出一个把websocket分离出来的版本？

**Comment by MarkRepo** [comment]
把websocket分离出来是什么意思？不用于浏览器吗？

**Comment by chenchenwuai** [comment]
分离websocket是因为我的项目中，websocket需要登录，然后解密websocket数据，解析数据包头，然后才能得到真实的视频数据，所以想自己创建websocket，然后解析出数据后再推给wfs。但是我自己水平有限，分离不出来websocket。目前我的解决方法是在wfs里面更改。但是这种耦合性有点太高了。

**Comment by MarkRepo** [comment]
我记得wfs.js 里面的websocket不需要解密啊，这不是取决于你有没有用ssl吗？我没太懂你的websocket 登录、解密是指什么？

**Comment by chenchenwuai** [comment]
我的意思是，我们的项目中会在原始视频头部加入一部分自定义的协议，然后在对这些数据进行非对称加密。我们的项目对安全要求比较高。

**Comment by MarkRepo** [comment]
明白你的意思了，这样的话你得改websockify这个开源代理的实现

**Comment by MarkRepo** [comment]
不过我觉得你在wfs里面解密也可以啊，本来websocket就只负责传输数据，不负载数据的解析，这是应用层的事情
